### ISSUE TITLE
Integrating a new volume driver

### ISSUE THREAD

**Issue by chrboe** [portworx/torpedo#471]
We have been trying to [get a LINSTOR volume driver upstreamed into stork](https://github.com/libopenstorage/stork/issues/618), but I'm having a little trouble running the torpedo tests.

I have managed to create a LINSTOR volume driver and get torpedo to run with it, but the deployments it does all seem highly portworx-specific (for example, [drivers/scheduler/k8s/specs/nginx/px-nginx-storage.yaml](https://github.com/portworx/torpedo/blob/master/drivers/scheduler/k8s/specs/nginx/px-nginx-storage.yaml)). Does that mean we will have to re-implement all the deployments for our storage driver? Am I missing something?

**Comment by disrani-px** [comment]
@chrboe you don't need to run the torpedo tests here. Just implement the driver for your volume and then vendor that in to stork. For an example you can see we run tests for the aws driver in stork. After adding your driver you would need to add a storage class under a directory with your driver name and start the test with the driver name.
