### ISSUE TITLE
Add support for StatefulSet

### ISSUE THREAD

**Issue by harsh-px** [portworx/torpedo#6]
In terms of application, support only exists for `Deployment`. We need support for `StatefulSet` and `Service`.

Support will mainly be in k8s driver implementation and k8sutils package.

**Comment by varunturlapati** [comment]
Checked in support for StatefulSet (reviewed by @harsh-px ). More can be added as needed.

**Comment by harsh-px** [comment]
The statefulset API's `ValidateStatefulSet` and `GetStatefulSetPods` don't work. I'll be fixing them now.
