### ISSUE TITLE
Possible mistake in error handling in the MultiProviderBackupKillStork test

### ISSUE THREAD

**Issue by thebsv** [portworx/torpedo#876]
There is a difference in error handling in the select block between this line:
https://github.com/portworx/torpedo/blob/20efba8789574afc875bc90edf69f44ee3c51741/tests/backup/backup_test.go#L457

and these lines,
https://github.com/portworx/torpedo/blob/20efba8789574afc875bc90edf69f44ee3c51741/tests/backup/backup_test.go#L587
https://github.com/portworx/torpedo/blob/20efba8789574afc875bc90edf69f44ee3c51741/tests/backup/backup_test.go#L776

Should the `Expect(err)` be `Expect(ctx.Err())` in lines 587, 776 similar to line 457?

I'm new to the codebase, so pardon me if I'm wrong 😄

**Comment by kshithijiyer-px** [comment]
The test was removed during the latest cleanup hence marking it as closed.
